service: sendNotification 

provider:

  name: aws   
  runtime: nodejs14.x   
  region: ap-northeast-2 
  # profile: jang
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource: ${ssm:/200OK/SNS/NotificationSend}
        - Effect: Allow
          Action:
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            - sqs:ReceiveMessage   
          Resource: arn:aws:sqs:ap-northeast-2:889058321615:sendNotification
  environment:
    SNS_TOPIC: ${ssm:/200OK/SNS/NotificationSend}

functions:   
  hello:     
   handler: handler.hello
   events:       
     - sqs:           
         arn:             
          Fn::GetAtt:               
             - sendNotification               
             - Arn  
resources:   
  Resources:     
    sendNotification:       
      Type: "AWS::SQS::Queue"       
      Properties:         
        QueueName: "sendNotification"
    SnsSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt sendNotification.Arn
        TopicArn: ${ssm:/200OK/SNS/DeliveryStatus}